name = "Journey MC"
author = "GameOnHunter"
version = "45.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05982a6164ac8ffbc17a4f464d55a6a0a75c11d9001f373d4566ca7b68a06163"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
