name = "Journey MC"
author = "GameOnHunter"
version = "39.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4e39d87c7a9839fdb18614e0c403caab19f872e5a8a3ef40349489f26b4bd97"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
