name = "Journey MC"
author = "GameOnHunter"
version = "28.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64fa0b6cd3182ab4b4ad74a8142ae11ccf96c6052ffb3d7afafa1d12b738d532"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
